name = "first-build"
main = "src/index.ts"
compatibility_date = "2024-12-31"
minify = true

# compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = "public"

[vars]
JWT_SECRET = "cape-quail-23109W%#@#"

[env.staging]
JWT_SECRET = "cape-quail-2093W@#"
haunted = false

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "siberia-tea-cup"
preview_bucket_name = "preview-tea-cup"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1